config/routes.rb
require "sidekiq/web"
require_dependency "scheduler/web"
require_dependency "admin_constraint"
require_dependency "staff_constraint"
require_dependency "homepage_constraint"

# This used to be User#username_format, but that causes a preload of the User object
# and makes Guard not work properly.
USERNAME_ROUTE_FORMAT = /[A-Za-z0-9\_]+/ unless defined? USERNAME_ROUTE_FORMAT
BACKUP_ROUTE_FORMAT = /[a-zA-Z0-9\-_]*\d{4}(-\d{2}){2}-\d{6}\.tar\.gz/i unless defined? BACKUP_ROUTE_FORMAT

Discourse::Application.routes.draw do

  match "/404", to: "exceptions#not_found", via: [:get, :post]
  get "/404-body" => "exceptions#not_found_body"

  if Rails.env == "development"
    mount Sidekiq::Web => "/sidekiq"
    mount Logster::Web => "/logs"
  else
    mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new
    mount Logster::Web => "/logs", constraints: AdminConstraint.new
  end

  get "site" => "site#index"

  resources :forums
  get "srv/status" => "forums#status"

  namespace :admin, constraints: StaffConstraint.new do
    get "" => "admin#index"

    resources :site_settings, constraints: AdminConstraint.new do
      collection do
        get "category/:id" => "site_settings#index"
      end
    end

    get "reports/:type" => "reports#show"

    resources :groups, constraints: AdminConstraint.new do
      collection do
        post "refresh_automatic_groups" => "groups#refresh_automatic_groups"
      end
      get "users"
    end

    resources :users, id: USERNAME_ROUTE_FORMAT do
      collection do
        get "list/:query" => "users#index"
        put "approve-bulk" => "users#approve_bulk"
        delete "reject-bulk" => "users#reject_bulk"
      end
      put "suspend"
      put "delete_all_posts"
      put "unsuspend"
      put "revoke_admin", constraints: AdminConstraint.new
      put "grant_admin", constraints: AdminConstraint.new
      post "generate_api_key", constraints: AdminConstraint.new
      delete "revoke_api_key", constraints: AdminConstraint.new
      put "revoke_moderation", constraints: AdminConstraint.new
      put "grant_moderation", constraints: AdminConstraint.new
      put "approve"
      post "refresh_browsers", constraints: AdminConstraint.new
      put "activate"
      put "deactivate"
      put "block"
      put "unblock"
      put "trust_level"
      put "primary_group"
      get "badges"
      get "leader_requirements"
    end

    resources :impersonate, constraints: AdminConstraint.new

    resources :email do
      collection do
        post "test"
        get "all"
        get "sent"
        get "skipped"
        get "preview-digest" => "email#preview_digest"
      end
    end

    scope "/logs" do
      resources :staff_action_logs,     only: [:index]
      resources :screened_emails,       only: [:index]
      resources :screened_ip_addresses, only: [:index, :create, :update, :destroy]
      resources :screened_urls,         only: [:index]
    end

    get "customize" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/css_html" => "site_customizations#index", constraints: AdminConstraint.new
    get "customize/colors" => "color_schemes#index", constraints: AdminConstraint.new
    get "flags" => "flags#index"
    get "flags/:filter" => "flags#index"
    post "flags/agree/:id" => "flags#agree"
    post "flags/disagree/:id" => "flags#disagree"
    post "flags/defer/:id" => "flags#defer"
    resources :site_customizations, constraints: AdminConstraint.new
    resources :site_contents, constraints: AdminConstraint.new
    resources :site_content_types, constraints: AdminConstraint.new
    resources :color_schemes, constraints: AdminConstraint.new

    get "version_check" => "versions#show"

    resources :dashboard, only: [:index] do
      collection do
        get "problems"
      end
    end

    resources :api, only: [:index], constraints: AdminConstraint.new do
      collection do
        post "key" => "api#create_master_key"
        put "key" => "api#regenerate_key"
        delete "key" => "api#revoke_key"
      end
    end

    resources :backups, only: [:index, :create], constraints: AdminConstraint.new do
      member do
        get "" => "backups#show", constraints: { id: BACKUP_ROUTE_FORMAT }
        delete "" => "backups#destroy", constraints: { id: BACKUP_ROUTE_FORMAT }
        post "restore" => "backups#restore", constraints: { id: BACKUP_ROUTE_FORMAT }
      end
      collection do
        get "logs" => "backups#logs"
        get "status" => "backups#status"
        get "cancel" => "backups#cancel"
        get "rollback" => "backups#rollback"
        put "readonly" => "backups#readonly"
        get "upload" => "backups#check_chunk"
        post "upload" => "backups#upload_chunk"
      end
    end

    resources :badges, constraints: AdminConstraint.new do
      collection do
        get "types" => "badges#badge_types"
      end
    end

    get "memory_stats"=> "diagnostics#memory_stats", constraints: AdminConstraint.new

  end # admin namespace

  get "email_preferences" => "email#preferences_redirect", :as => "email_preferences_redirect"
  get "email/unsubscribe/:key" => "email#unsubscribe", as: "email_unsubscribe"
  post "email/resubscribe/:key" => "email#resubscribe", as: "email_resubscribe"

  resources :session, id: USERNAME_ROUTE_FORMAT, only: [:create, :destroy] do
    collection do
      post "forgot_password"
    end
  end

  get "session/sso" => "session#sso"
  get "session/sso_login" => "session#sso_login"
  get "session/current" => "session#current"
  get "session/csrf" => "session#csrf"
  get "composer-messages" => "composer_messages#index"

  resources :users, except: [:show, :update, :destroy] do
    collection do
      get "check_username"
      get "is_local_username"
    end
  end

  resources :static
  post "login" => "static#enter"
  get "login" => "static#show", id: "login"
  get "faq" => "static#show", id: "faq"
  get "tos" => "static#show", id: "tos"
  get "privacy" => "static#show", id: "privacy"
  get "signup" => "list#latest"

  get "users/search/users" => "users#search_users"
  get "users/password-reset/:token" => "users#password_reset"
  put "users/password-reset/:token" => "users#password_reset"
  get "users/activate-account/:token" => "users#activate_account"
  get "users/authorize-email/:token" => "users#authorize_email"
  get "users/hp" => "users#get_honeypot_value"
  get "my/:path", to: 'users#my_redirect'

  get "user_preferences" => "users#user_preferences_redirect"
  get "users/:username/private-messages" => "user_actions#private_messages", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/private-messages/:filter" => "user_actions#private_messages", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username" => "users#show", as: 'userpage', constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username" => "users#update", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/preferences" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}, as: :email_preferences
  get "users/:username/preferences/email" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username/preferences/email" => "users#change_email", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/preferences/about-me" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/preferences/badge_title" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username/preferences/badge_title" => "users#badge_title", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/preferences/username" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username/preferences/username" => "users#username", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/avatar(/:size)" => "users#avatar", constraints: {username: USERNAME_ROUTE_FORMAT} # LEGACY ROUTE
  post "users/:username/preferences/avatar" => "users#upload_avatar", constraints: {username: USERNAME_ROUTE_FORMAT} # LEGACY ROUTE
  post "users/:username/preferences/user_image" => "users#upload_user_image", constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username/preferences/avatar/toggle" => "users#toggle_avatar", constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username/preferences/profile_background/clear" => "users#clear_profile_background", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/invited" => "users#invited", constraints: {username: USERNAME_ROUTE_FORMAT}
  post "users/:username/send_activation_email" => "users#send_activation_email", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/activity" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/activity/:filter" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/badges" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  delete "users/:username" => "users#destroy", constraints: {username: USERNAME_ROUTE_FORMAT}

  get "uploads/:site/:id/:sha.:extension" => "uploads#show", constraints: {site: /\w+/, id: /\d+/, sha: /[a-z0-9]{15,16}/i, extension: /\w{2,}/}
  post "uploads" => "uploads#create"

  get "posts/by_number/:topic_id/:post_number" => "posts#by_number"
  put "posts/by_number/:topic_id/:post_number/bookmarks/remove" => "posts#remove_bookmark_by_number"
  get "posts/:id/reply-history" => "posts#reply_history"

  resources :groups do
    get 'members'
    get 'posts'
    get 'counts'
  end

  resources :posts do
    put "bookmark"
    put "wiki"
    get "replies"
    get "revisions/:revision" => "posts#revisions"
    put "recover"
    collection do
      delete "destroy_many"
    end
  end

  get "p/:post_id/:user_id" => "posts#short_link"

  resources :notifications

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= SiteSetting.default_locale %>" class="<%= html_classes %>">
  <head>
    <meta charset="utf-8">
    <title><%= content_for?(:title) ? yield(:title) + ' - ' + SiteSetting.title : SiteSetting.title %></title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="<%= @description_meta || SiteSetting.site_description %>" name="description">
    <meta content="" name="author">

    <%- if SiteSetting.enable_escaped_fragments? %>
    <meta name="fragment" content="!">
    <%- end %>

    <%= canonical_link_tag %>

    <link rel="icon" type="image/png" href="<%=SiteSetting.favicon_url%>">
    <link rel="apple-touch-icon" type="image/png" href="<%=SiteSetting.apple_touch_icon_url%>">

    <%= script "preload_store" %>
    <%= javascript_include_tag "locales/#{I18n.locale}" %>
    <%= script "vendor" %>
    <%= script "application" %>
    <%- if staff? %>
      <%= script "admin"%>
    <%- end %>

    <%= render :partial => "common/special_font_face" %>
    <%= render :partial => "common/discourse_stylesheet" %>

    <%= discourse_csrf_tags %>

    <%= raw SiteContent.content_for(:head) %>

    <%= render_google_universal_analytics_code %>

    <%= yield :head %>
  </head>

  <body>
    <noscript data-path="<%= request.env['PATH_INFO'] %>">
      <header class="d-header">
        <div class="container">
          <div class="contents">
            <div class="row">
              <div class="title span13">
                <a href="/"><img src="<%=SiteSetting.logo_url%>" alt="<%=SiteSetting.title%>" id="site-logo"></a>
              </div>
            </div>
          </div>
        </div>
      </header>
      <div id="main-outlet" class="container">
        <!-- preload-content: -->
        <%= yield %>
        <!-- :preload-content -->
      </div>
    </noscript>

    <!--[if IE 9]><script type="text/javascript">ie = "new";</script><![endif]-->

    <%- unless customization_disabled? %>
      <%= SiteCustomization.custom_header(session[:preview_style], mobile_view? ? :mobile : :desktop) %>
    <%- end %>

    <section id='main'>
    </section>

    <% unless current_user %>
      <form id='hidden-login-form' method="post" action="<%=login_path%>" style="display: none;">
        <input name="username" type="text"     id="signin_username">
        <input name="password" type="password" id="signin_password">
        <input name="redirect" type="hidden">
        <input type="submit" id="signin-button" value="Sign In">
      </form>
    <% end %>

    <%- if @preloaded.present? %>
      <script>
      <%- @preloaded.each do |key, json| %>
        PreloadStore.store("<%= key %>",<%= escape_unicode(json) %>);
      <% end %>
      </script>
    <%- end %>

    <%= yield :data %>

    <footer id='bottom'></footer>

    <%= render :partial => "common/discourse_javascript" %>

    <%= render_google_analytics_code %>

    <!-- Discourse Version: <%= Discourse::VERSION::STRING %> -->
    <!-- Git Version: <%= Discourse.git_version %> -->
  </body>
</html>

app/views/layouts/crawler.html.erb
<!DOCTYPE html>
<html lang="<%= SiteSetting.default_locale %>">
  <head>
    <meta charset="utf-8">
    <title><%= content_for?(:title) ? yield(:title) + ' - ' + SiteSetting.title : SiteSetting.title %></title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="<%= @description_meta || SiteSetting.site_description %>" name="description">
    <meta content="" name="author">

    <%= canonical_link_tag %>

    <link rel="icon" type="image/png" href="<%=SiteSetting.favicon_url%>">
    <link rel="apple-touch-icon" type="image/png" href="<%=SiteSetting.apple_touch_icon_url%>">

    <%= render :partial => "common/special_font_face" %>
    <%= render :partial => "common/discourse_stylesheet" %>
    <%= discourse_csrf_tags %>
    <%= raw SiteContent.content_for(:head) %>
    <%= yield :head %>
  </head>
  <body>
    <%- unless customization_disabled? %>
      <%= SiteCustomization.custom_header(session[:preview_style]) %>
    <%- end %>
    <header class="d-header">
      <div class="container">
        <div class="contents">
          <div class="row">
            <div class="title span13">
              <a href="/"><img src="<%=SiteSetting.logo_url%>" alt="<%=SiteSetting.title%>" id="site-logo"></a>
            </div>
          </div>
        </div>
      </div>
    </header>
    <div id="main-outlet" class="container">
      <!-- preload-content: -->
      <%= yield %>
      <!-- :preload-content -->
    </div>
  </body>
</html>

app/views/layouts/embed.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'embed' %>
    <%= javascript_include_tag 'break_string' %>

    <script>
      (function() {

        function postUp(msg) {
          if (parent) {
            parent.postMessage(msg, '<%= request.referer %>');
          }
        }

        function clickPostLink(e) {
          var postId = e.target.getAttribute('data-link-to-post');
          if (postId) {
            var postElement = document.getElementById('post-' + postId);
            if (postElement) {
              var rect = postElement.getBoundingClientRect();
              if (rect && rect.top) {
                postUp({type: 'discourse-scroll', top: rect.top});
                e.preventDefault();
                return false;
              }
            }
          }
        }

        window.onload = function() {
          // Send a post message with our loaded height
          postUp({type: 'discourse-resize', height: document['body'].offsetHeight});

          var postLinks = document.querySelectorAll("a[data-link-to-post]"),
              i;

          for (i=0; i<postLinks.length; i++) {
            postLinks[i].onclick = clickPostLink;
          }

          // Make sure all links in the iframe point to _blank
          var cookedLinks = document.querySelectorAll('.cooked a');
          for (i=0; i<cookedLinks.length; i++) {
            cookedLinks[i].target = "_blank";
          }

          // Adjust all names
          var names = document.querySelectorAll('.username a');
          for (i=0; i<names.length; i++) {
            var username = names[i].innerHTML;
            if (username) {
              names[i].innerHTML = new BreakString(username).break();
            }
          }

        };

      })();
    </script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/no_js.html.erb
<!DOCTYPE html>
<html lang="<%= SiteSetting.default_locale %>">
  <head>
    <meta charset="utf-8">
    <title><%=SiteSetting.title%></title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">
    <link rel="icon" type="image/png" href=<%=SiteSetting.favicon_url%>>
    <%= render :partial => "common/special_font_face" %>
    <%= render :partial => "common/discourse_stylesheet" %>
    <%= discourse_csrf_tags %>
    <%= raw SiteContent.content_for(:head) %>
  </head>
  <body>
    <%- unless customization_disabled? %>
      <%= SiteCustomization.custom_header(session[:preview_style]) %>
    <%- end %>
    <section id='main'>
      <header class="d-header">
        <div class="container">
          <div class="contents">
            <div class="row">
              <div class="title span13">
                <a href="/"><img src="<%=SiteSetting.logo_url%>" alt="<%=SiteSetting.title%>" id="site-logo"></a>
              </div>
              <% unless current_user %>
                <div class='panel clearfix'>
                  <a href="/login" class='btn btn-primary btn-small'><i class="fa fa-user"></i><%= I18n.t('log_in') %></a>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </header>
      <div id="main-outlet" class="container">
        <%= yield %>
      </div>
    </section>
    <footer id='bottom'>
    </footer>
  </body>
</html>